### ISSUE TITLE
Progress/status indicator

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#16]
When the API returns long replies, there can be long periods of waiting where I don't know whether its taking so long because my internet went down, or because the reply is really long.

It would be useful if there were some progress or status indicator to each job displayed in the mode line.

**Comment by tyler-dodge** [comment]
The latest version has `org-assistant-mode` which is a minor mode that changes the mode line to including a queue that shows the individual requests.
It shows the first four letters of the UUID of each request in the [].

Below is the part of the mode-line-format I mentioned:
```
    (:eval (concat "[" (s-join "," (--map (substring it 0 4) org-assistant--inflight-request)) "]") )
```

Closing since I think this is already complete

**Comment by walseb** [comment]
Yes although the mode line only displays what jobs are currently running. It would be more useful to know exactly what stage they are in. E.g. connecting to API, waiting for reply, etc. 

I'd imagine the mode line would then say something like [foo123(C)] for connecting, for instance.

It's less of an issue once the streaming branch is merged, but it could still be useful in case you have a slow internet connection/DNS issues.

But I'm quite unfamiliar with the interface for making web requests, do you have access to any of that information when making a request?

**Comment by tyler-dodge** [comment]
Yeah, it'd be possible now with the streaming API / it does give some feedback that correlates with the states of the request like once the src block shows up, the server is necessarily connected

More work could be done via adding verbose flags to curl, and parsing the output. For the moment, I only intend to do the streaming implementation, since I think that gives it significantly more feedback than it had before.
