### ISSUE TITLE
Undo and streaming

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#29]
Hello!

Sometimes I press undo while something is being streamed in.

That irreversibly deletes part of what's been generated, as the text will keep getting streamed in while I try to recover it through redoing.

Is there a solution to this? Perhaps the streaming should be wrapped in `with-undo-amalgamate`, so that it all gets undone in one go? That might be slightly better, as it's then clear what you just undid.

Another, more pressing problem is that streaming creates a ton of undo points, meaning you have to press undo many times to undo a long stream of text.

Thoughts on this?

**Comment by tyler-dodge** [comment]
Unfortunately since it's using deferred for async, we can't rely on macro scope for the boundary since it doesn't rely on inner loops. 

Overlays will work better for this since they do not affect undo history.

I'm no longer using the stream id in the header to avoid an extra undo step as well, so that the only insert that happens is when the response is finished.

This should make it so that an entire request is undoable, and that if a request is currently active, undoing will cancel it the next time it receives output from OpenAI.

https://github.com/tyler-dodge/org-assistant/commit/5c42133b2dd8a751ea87435bd994dac830bd3936

**Comment by walseb** [comment]
Wow, that sounds amazing! I will try it out.

**Comment by tyler-dodge** [comment]
There is a bug right now with undoing where it's possible an overlay will be left over in the buffer. I'm working on a fix now, but if you run into it, you can remove the overlay at point with

`(--map (delete-overlay it) (overlays-in (point) (point)))`

**Comment by tyler-dodge** [comment]
That should no longer happen as of https://github.com/tyler-dodge/org-assistant/commit/5c1ab2184569831639a6b4ee626a0b42c9719918
