### ISSUE TITLE
OpenAI bullet pointed lists aren't formatted properly

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#3]
It appears as if OpenAI has some special formatting when sending lists. 

The items all appear on the same line:
```
#+BEGIN_SRC assistant
Make a bullet point list of the 10 most common names in the US
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
Here is a list of the 10 most common names in the US, based on data from the
Social Security Administration:

1. Emma 2. Olivia 3. Noah 4. Liam 5. Ava 6. Sophia 7. Isabella 8. Jackson 9.
Lucas 10. Aiden

Note: This list is based on data from 2020 and may change slightly year to year.
#+END_EXAMPLE
```

I'm using the latest commit: https://github.com/tyler-dodge/org-assistant/commit/aac1ce642c92b6814fae355c4b62a693bcf22b41

**Comment by walseb** [comment]
It doesn't appear to be the fault of OpenAI. What's at this line https://github.com/tyler-dodge/org-assistant/blob/aac1ce642c92b6814fae355c4b62a693bcf22b41/org-assistant.el#L185 has newlines:
(...
 (model . "gpt-3.5-turbo-0301")
 (usage
  (prompt_tokens . 435)
  (completion_tokens . 40)
  (total_tokens . 475))
 (choices .
	  [((message
	     (role . "assistant")
	     (content . "1. Emma
2. Liam
3. Olivia
4. Noah
5. Ava
6. Ethan
7. Sophia
8. Mason
9. Isabella
10. William"))
	    (finish_reason . "stop")
	    (index . 0))]))

**Comment by tyler-dodge** [comment]
Thanks for the initial investigation and bug report.

Yeah, it turns out string-fill was removing all newlines in order to make it as dense as possible (living up to its name). This commit switches over to using visual-line-mode for line wrapping instead, so formatting is preserved:
 
https://github.com/tyler-dodge/org-assistant/commit/0bc3daedbf34c3d08d3f55b9226bdbe1f4e04832

**Comment by walseb** [comment]
Excellent!

I tried it and it works well now.
