### ISSUE TITLE
First Impressions 

### ISSUE THREAD

**Issue by NightMachinery** [tyler-dodge/org-assistant#9]
1. Using the tree structure is great. 
2. Using ‘?’ feels invasive. This should be behind a flag that is by default disabled. 
3. The model used for the request must be specifiable using a header argument of the source block and also a heading property that sets the default model fir all subtrees. 
4. The answer must also be a source block, as you can complete an assistant message, too!
5. The message type must be a header argument of the source block. 
6. Image generation must use a different lang name, not assistant. It should also support specifying the model used.
7. What’s the backend? Ideally must be use a modular backend that supports different models including local.
8. ♥️

**Comment by tyler-dodge** [comment]
Thanks for the feedback, I am glad you are finding it useful.

Makes sense, I'd prefer to separate these into separate issues so I can complete them individually instead of relying on this. Could you do that for me?

2. I'd agree with if you can provide me with an example of any other org babel library that is in contention with it. If you are personally impacted, you can use `(fmakunbound #'org-babel-execute:?)`
3. makes sense to me
4. makes sense to me 
5. makes sense to me
6. Disagree, I prefer keeping the image generation based on output type. I'd accept a pull request though that adds an additional babel execute function that is specific for images.
7. It's making REST requests directly against the endpoint using curl. It wouldn't take much to switch out the code to point to a different one, but ideally the other endpoints would match OpenAI's API. Currently the endpoints are custom variables.

**Comment by tyler-dodge** [comment]
3-5,7 are all now implemented as of https://github.com/tyler-dodge/org-assistant/releases/tag/1.1

Closing this for now
